chnages 4

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -23,13 +23,13 @@ jobs:
       run: npm install
     
     - name: Run test & store log
-      run: npm run check > results.txt || echo "TEST FAILD"
+      run: npm run check > results1.txt || echo "TEST FAILD"
 
     - name: upload test results
       uses: actions/upload-artifact@v4
       with:
         name: test-results
-        path: results.txt
+        path: results1.txt
 
  #deploy
 
